name: bench

services:
  front:
    build:
      context: .
    depends_on:
      - config
    command: /opt/front http://config:2379
    ports:
      - "8089:8089"

  worker1:
    build:
      context: .
    depends_on:
      - config
    volumes:
      - ./docker/scripting-file.py:/opt/python/main.py:ro
    command: /opt/worker http://config:2379

  worker2:
    build:
      context: .
    depends_on:
      - config
    volumes:
      - ./docker/scripting-file.py:/opt/python/main.py:ro
    command: /opt/worker http://config:2379

  janitor:
    build:
      context: .
    depends_on:
      - config
    command: /opt/janitor http://config:2379

  config:
    image: gcr.io/etcd-development/etcd:v3.7.1
    volumes:
      - etcd-data:/etcd-data
    command:
      - /usr/local/bin/etcd
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://127.0.0.1:2379
      - --data-dir=/etcd-data

  storage:
    image: chrislusf/seaweedfs:latest

  rmq-entry:
    image: haproxy:3.0
    volumes:
      - ./docker/rmq-entry.haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rmq1
      - rmq2
      - rmq3

  rmq1:
    image: rabbitmq:management
    environment:
      RABBITMQ_ERLANG_COOKIE: 99X9gv]QGdKEuT3wyw0xicPjLLYpsewK
      RABBITMQ_NODENAME: rabbit@rmq1
      RABBITMQ_CONFIG_FILE: /rmq.conf
    ports:
      - "15673:15672"
    volumes:
      - ./docker/rmq.conf:/rmq.conf
      - ./docker/rmq.defs.json:/rmq.defs.json

  rmq2:
    image: rabbitmq:management
    environment:
      RABBITMQ_ERLANG_COOKIE: 99X9gv]QGdKEuT3wyw0xicPjLLYpsewK
      RABBITMQ_NODENAME: rabbit@rmq2
      RABBITMQ_CONFIG_FILE: /rmq.conf
    ports:
      - "15674:15672"
    volumes:
      - ./docker/rmq.conf:/rmq.conf
      - ./docker/rmq.defs.json:/rmq.defs.json

  rmq3:
    image: rabbitmq:management
    environment:
      RABBITMQ_ERLANG_COOKIE: 99X9gv]QGdKEuT3wyw0xicPjLLYpsewK
      RABBITMQ_NODENAME: rabbit@rmq3
      RABBITMQ_CONFIG_FILE: /rmq.conf
    ports:
      - "15675:15672"
    volumes:
      - ./docker/rmq.conf:/rmq.conf
      - ./docker/rmq.defs.json:/rmq.defs.json

  registrator:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql18/docker
    volumes:
      - ./docker/init-db.sql:/r20260921-init.sql
      - registrator-data:/var/lib/postgresql18/docker
    ports:
      - "5432:5432"

  prom:
    image: prom/prometheus:v3-busybox
    container_name: prometheus
    volumes:
      - ./docker/prom.yaml:/etc/prometheus/prom.yml
      - prom-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prom.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=15d
    restart: unless-stopped
    ports:
      - "9090:9090"

  graf:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: nimda
    restart: unless-stopped
    volumes:
      - graf-data:/var/lib/grafana
      - ./docker/graf-prom.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
      - ./docker/graf-dashboard.yaml:/etc/grafana/provisioning/dashboards/graf-dashboard.yaml
      - ./docker/graf-dashboard.json:/var/lib/grafana/dashboards/auto/r20260921.json:ro

volumes:
  prom-data:
  graf-data:
  etcd-data:
  registrator-data:
