global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "front"
    static_configs:
      - targets: ["front:8099"]
  - job_name: "worker"
    static_configs:
      - targets: ["worker1:8099", "worker2:8099"]
  - job_name: "janitor"
    static_configs:
      - targets: ["janitor:8099"]
