name: testbench

services:
  entry1:
    image: ghcr.io/s20260526/m20260618-entry:latest
    volumes:
      - ./ssl/ca.crt:/ca.crt
      - ./ssl/jwt.key:/jwt.key
      - ./ssl/jwt.pub:/jwt.pub
      - ./ssl/entry.crt:/client.crt
      - ./ssl/entry.key:/client.key

  entry2:
    image: ghcr.io/s20260526/m20260618-entry:latest
    volumes:
      - ./ssl/ca.crt:/ca.crt
      - ./ssl/jwt.key:/jwt.key
      - ./ssl/jwt.pub:/jwt.pub
      - ./ssl/entry.crt:/client.crt
      - ./ssl/entry.key:/client.key

  hello:
    image: ghcr.io/s20260526/m20260618-hello:latest
    volumes:
      - ./ssl/ca.crt:/ca.crt
      - ./ssl/hello.crt:/server.crt
      - ./ssl/hello.key:/server.key

  world:
    image: ghcr.io/s20260526/m20260618-world:latest
    volumes:
      - ./ssl/ca.crt:/ca.crt
      - ./ssl/world.crt:/server.crt
      - ./ssl/world.key:/server.key

  h:
    image: haproxy:3.0
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./ssl/entry.pem:/usr/local/etc/haproxy/certs/domain.pem:ro
    ports:
      - "8080:8080"
    depends_on:
      - entry1
      - entry2

  t:
    image: ubuntu:latest
    tty: true
    volumes:
      - ./ssl/ca.crt:/ca.crt

  l:
    image: grafana/loki:3.7
    container_name: loki
    volumes:
      - loki-data:/loki
    restart: unless-stopped
    logging:
      driver: none

  f:
    image: ghcr.io/fluent/fluent-bit:4.2
    container_name: fluent-bit
    cap_add:
      - CAP_FOWNER
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./fluent-bit.yaml:/fluent-bit/etc/fluent-bit.yaml:ro
      - fluent-bit-state:/var/fluent-bit/state
    depends_on:
      - l
    restart: unless-stopped
    command:
      - -c
      - /fluent-bit/etc/fluent-bit.yaml
    deploy:
      resources:
        limits:
          memory: 128M
    logging:
      driver: none

  p:
    image: prom/prometheus:v3-busybox
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=15d
    restart: unless-stopped
    ports:
      - "9090:9090"

  g:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "9060:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: nimda
    depends_on:
      - l
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-loki.yaml:/etc/grafana/provisioning/datasources/loki.yaml
      - ./grafana-prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
    logging:
      driver: none

volumes:
  loki-data:
  fluent-bit-state:
  prometheus_data:
  grafana-data:
