service:
  flush: 5s
  log_level: info
  daemon: off

parsers:

  - name: docker
    format: json
    time_key: time
    time_format: '%Y-%m-%dT%H:%M:%S.%L %z'
    time_keep: on
    decode_field_as: json log

  - name: purejson
    format: json

pipeline:

  inputs:

    - name: tail
      tag: log
      path: /var/lib/docker/containers/*/*-json.log
      parser: docker
      db: /var/fluent-bit/state/flb-docker.db
      mem_buf_limit: 5MB
      skip_long_lines: on
      refresh_interval: 10

    - name: tail
      tag: sink
      path: /sink.txt
      parser: purejson
      db: /var/fluent-bit/state/flb-sink.db
      mem_buf_limit: 5MB
      skip_long_lines: off
      refresh_interval: 1
      buffer_chunk_size: 1MB
      buffer_max_size: 50MB

  filters:
    - name: lua
      match: log
      call: tweak
      code: |
        function tweak(tag, timestamp, record)
            record["stream"] = nil
            record["time"] = nil

            return 1, timestamp, record
        end

  outputs:

    - name: loki
      match: log
      host: loki
      port: 3100
      uri: /loki/api/v1/push
      labels: app=m20260618

    - name: es
      match: sink
      host: elasticsearch
      index: sink
      suppress_type_name: on
