global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    metrics_path: "prometrics"
    static_configs:
      - targets: ["entry1:8080", "entry2:8080"]
