name: intest

on:
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  main:
    runs-on: ubuntu-latest

    services:
      entry:
        image: ghcr.io/s20260526/m20260618-entry:latest
        options:
          - --mount
          - type=secret,id=CA_CRT,target=/ca.crt
          - --mount
          - type=secret,id=ENTRY_CRT,target=/client.crt
          - --mount
          - type=secret,id=ENTRY_KEY,target=/client.key
        ports:
          - 8080:8080
      hello:
        image: ghcr.io/s20260526/m20260618-hello:latest
        options:
          - --mount
          - type=secret,id=CA_CRT,target=/ca.crt
          - --mount
          - type=secret,id=HELLO_CRT,target=/server.crt
          - --mount
          - type=secret,id=HELLO_KEY,target=/server.key
      world:
        image: ghcr.io/s20260526/m20260618-world:latest
        options:
          - --mount
          - type=secret,id=CA_CRT,target=/ca.crt
          - --mount
          - type=secret,id=WORLD_CRT,target=/server.crt
          - --mount
          - type=secret,id=WORLD_KEY,target=/server.key

    steps:
      - name: run
        run: test "$(wget -O - -q http://127.0.0.1:8080)" = 'Hello, World!'
